#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["marketplace-backend/marketplace-backend.csproj", "marketplace-backend/"]
RUN dotnet restore "marketplace-backend/marketplace-backend.csproj"
COPY . .
WORKDIR "/src/marketplace-backend"
RUN dotnet build "marketplace-backend.csproj" -c Debug -o /app

FROM build AS publish
RUN dotnet publish "marketplace-backend.csproj" -c Debug -o /app

FROM mcr.microsoft.com/dotnet/core/runtime:3.1 AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "marketplace-backend.dll"]
